<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\ReviewController' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Controller/ReviewController.php';

return $this->services['AppBundle\Controller\ReviewController'] = new \AppBundle\Controller\ReviewController();
