<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxcwq7u\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxcwq7u/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUxcwq7u.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUxcwq7u\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUxcwq7u\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Uxcwq7u',
    'container.build_id' => 'a9567651',
    'container.build_time' => 1524499907,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxcwq7u');
